//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamnTools.SqlTodoExplorer.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DamnTools.SqlTodoExplorer.Services.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to master,model,msdb,tempdb.
        /// </summary>
        public static string Database_ExclusionList {
            get {
                return ResourceManager.GetString("Database_ExclusionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ArrayOfTodoPattern&gt;
        ///    &lt;TodoPattern default=&quot;true&quot;&gt;
        ///        &lt;Title&gt;Todo&lt;/Title&gt;
        ///        &lt;SearchPattern&gt;&lt;![CDATA[(?&lt;=\W|^)(?&lt;TAG&gt;TODO)(.*)]]&gt;&lt;/SearchPattern&gt;
        ///    &lt;/TodoPattern&gt;
        ///    &lt;TodoPattern&gt;
        ///        &lt;Title&gt;Hack&lt;/Title&gt;
        ///        &lt;SearchPattern&gt;&lt;![CDATA[(?&lt;=\W|^)(?&lt;TAG&gt;HACK)(.*)]]&gt;&lt;/SearchPattern&gt;
        ///    &lt;/TodoPattern&gt;
        ///    &lt;TodoPattern&gt;
        ///        &lt;Title&gt;Ask&lt;/Title&gt;
        ///        &lt;SearchPattern&gt;&lt;![CDATA[(?&lt;=\W|^)(?&lt;TAG&gt;ASK)(.*)]]&gt;&lt;/SearchPattern&gt;
        ///    &lt;/TodoPattern&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaultTodoPatterns {
            get {
                return ResourceManager.GetString("DefaultTodoPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\s*CREATE(?=\s*(?:PROCEDURE|PROC|FUNCTION|FUNC)).
        /// </summary>
        public static string ScriptAsAlter_ReplaceRegex {
            get {
                return ResourceManager.GetString("ScriptAsAlter_ReplaceRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [{0}] -- Database name
        ///SELECT
        ///	  ROUTINE_OBJECTID		= SC.id
        ///	, SR.ROUTINE_SCHEMA
        ///	, SR.ROUTINE_NAME
        ///	, ROUTINE_FULLNAME		= SR.ROUTINE_SCHEMA + &apos;.&apos; + SR.ROUTINE_NAME
        ///	, SR.ROUTINE_TYPE
        ///	, SC.colid
        ///	, ROUTINE_DEFINITION	= SC.[text]
        ///FROM
        ///	INFORMATION_SCHEMA.ROUTINES	SR
        ///	JOIN sys.syscomments		SC	ON SC.id = OBJECT_ID(ROUTINE_SCHEMA + &apos;.&apos; + ROUTINE_NAME)
        ///WHERE
        ///	SC.id = {1} -- OBJECT_ID
        ///ORDER BY
        ///	ROUTINE_OBJECTID, colid.
        /// </summary>
        public static string SQL_Routine {
            get {
                return ResourceManager.GetString("SQL_Routine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [{0}] -- Database name
        ///SELECT
        ///	  ROUTINE_OBJECTID		= SC.id
        ///	, SR.ROUTINE_SCHEMA
        ///	, SR.ROUTINE_NAME
        ///	, ROUTINE_FULLNAME		= SR.ROUTINE_SCHEMA + &apos;.&apos; + SR.ROUTINE_NAME
        ///	, SR.ROUTINE_TYPE
        ///	, SC.colid
        ///	, ROUTINE_DEFINITION	= SC.[text]
        ///FROM
        ///	INFORMATION_SCHEMA.ROUTINES	SR
        ///	JOIN sys.syscomments		SC	ON SC.id = OBJECT_ID(ROUTINE_SCHEMA + &apos;.&apos; + ROUTINE_NAME)
        ///ORDER BY
        ///	ROUTINE_OBJECTID, colid.
        /// </summary>
        public static string SQL_Routines {
            get {
                return ResourceManager.GetString("SQL_Routines", resourceCulture);
            }
        }
    }
}
